# -*- coding: utf-8 -*-
"""dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b14jRkiLtIxnIb-a6Pb1mBzqzGxnHNtw
"""

"""
Customer Transaction Prediction — Dashboard
============================================
Banking ML project · Built with Streamlit + Matplotlib
Run: streamlit run dashboard.py
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ============================================================
# PAGE CONFIG
# ============================================================
st.set_page_config(
    page_title="Customer Transaction Prediction | Dashboard",
    page_icon="🏦",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================
# COLORS
# ============================================================
PRIMARY   = '#6366f1'
SECONDARY = '#8b5cf6'
SUCCESS   = '#10b981'
DANGER    = '#ef4444'
WARNING   = '#f59e0b'
INFO      = '#06b6d4'

plt.rcParams.update({
    'figure.facecolor':  'white',
    'axes.facecolor':    '#f8fafc',
    'axes.edgecolor':    '#e2e8f0',
    'axes.titleweight':  'bold',
    'axes.titlesize':    12,
    'axes.labelcolor':   '#475569',
    'axes.labelsize':    10,
    'xtick.color':       '#64748b',
    'ytick.color':       '#64748b',
    'grid.color':        '#e2e8f0',
    'grid.alpha':        0.5,
    'font.family':       'DejaVu Sans',
})

st.markdown("""
<style>
.main-title {
    background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #ec4899 100%);
    padding: 1.8rem 1.5rem;
    border-radius: 16px;
    color: white;
    margin-bottom: 1.5rem;
    box-shadow: 0 10px 30px rgba(99,102,241,0.25);
}
.main-title h1 {
    color: white !important;
    margin: 0;
    font-size: 1.8rem;
    font-weight: 800;
}
.main-title p {
    color: rgba(255,255,255,0.9) !important;
    margin: 0.4rem 0 0 0;
}
.badge {
    display: inline-block;
    background: rgba(255,255,255,0.2);
    color: white !important;
    padding: 0.2rem 0.7rem;
    border-radius: 12px;
    font-size: 0.75rem;
    font-weight: 600;
    margin: 0.4rem 0.3rem 0 0;
}
.kpi-card {
    background: white;
    border: 1px solid #e2e8f0;
    border-left: 4px solid #6366f1;
    border-radius: 12px;
    padding: 1rem 1.2rem;
    box-shadow: 0 2px 8px rgba(0,0,0,0.04);
}
.kpi-value {
    font-size: 1.8rem;
    font-weight: 800;
    color: #6366f1;
    margin: 0;
}
.kpi-label {
    font-size: 0.8rem;
    color: #64748b;
    margin: 0;
    font-weight: 500;
}
.insight {
    background: #f0f9ff;
    border-left: 4px solid #06b6d4;
    padding: 0.9rem 1.1rem;
    border-radius: 8px;
    margin: 0.8rem 0;
    color: #0c4a6e;
    line-height: 1.6;
}
.section-h {
    color: #1e293b;
    font-weight: 700;
    font-size: 1.2rem;
    margin: 1.5rem 0 0.8rem 0;
    padding-bottom: 0.4rem;
    border-bottom: 2px solid #6366f1;
}
[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #1e293b 0%, #0f172a 100%);
}
[data-testid="stSidebar"] * { color: white !important; }
[data-testid="stSidebar"] a { color: #a5b4fc !important; }
</style>
""", unsafe_allow_html=True)


# ============================================================
# DATA
# ============================================================
@st.cache_data
def get_results():
    return {
        'LightGBM':            {'auc': 0.8856, 'ap': 0.5818, 'acc': 0.9222, 'cv_auc': 0.8815, 'cv_std': 0.0031, 'color': PRIMARY},
        'XGBoost':             {'auc': 0.8818, 'ap': 0.5744, 'acc': 0.9222, 'cv_auc': 0.8794, 'cv_std': 0.0028, 'color': SECONDARY},
        'Logistic Regression': {'auc': 0.8684, 'ap': 0.5326, 'acc': 0.9184, 'cv_auc': 0.8667, 'cv_std': 0.0025, 'color': INFO},
        'Random Forest':       {'auc': 0.8611, 'ap': 0.5309, 'acc': 0.8995, 'cv_auc': 0.8635, 'cv_std': 0.0041, 'color': WARNING},
    }

@st.cache_data
def get_simulated_proba(n=10000, true_rate=0.101, seed=42):
    rng = np.random.default_rng(seed)
    n_pos = int(n * true_rate)
    n_neg = n - n_pos
    pos = np.clip(rng.beta(2.5, 2, n_pos) * 0.9 + 0.05, 0, 1)
    neg = np.clip(rng.beta(1.5, 8, n_neg), 0, 1)
    proba = np.concatenate([pos, neg])
    y = np.concatenate([np.ones(n_pos), np.zeros(n_neg)])
    idx = rng.permutation(n)
    return proba[idx], y[idx]

FEATURE_IMPORTANCE = {
    'var_81': 312, 'var_139': 289, 'var_12': 275, 'pc_1': 252,
    'var_53': 241, 'var_26': 235, 'var_174': 228, 'var_76': 219,
    'var_110': 208, 'var_0': 199, 'var_6': 192, 'var_40': 183,
    'var_22': 176, 'var_148': 169, 'var_179': 163, 'var_9': 158,
    'var_166': 151, 'var_67': 145, 'var_99': 139, 'var_133': 133,
    'var_47': 128, 'var_88': 121, 'var_115': 115, 'anomaly_score': 101,
    'row_mean': 95,
}

DECILE_RATES = [0.001, 0.005, 0.015, 0.020, 0.025, 0.038, 0.070, 0.105, 0.180, 0.559]


# ============================================================
# SIDEBAR
# ============================================================
with st.sidebar:
    st.markdown("# 🏦 Dashboard")
    st.markdown("---")
    st.markdown("### 📌 Project")
    st.markdown("""
**Customer Transaction Prediction**
**Domain:** Banking / FinTech
**Type:** Binary Classification
**Dataset:** 200K × 202
**Positive Rate:** ~10%
""")
    st.markdown("---")
    st.markdown("### 🏆 Best Model")
    st.metric("LightGBM AUC", "0.8856", "+0.0038 vs XGBoost")
    st.metric("Avg Precision", "0.5818", "+0.0074 vs XGBoost")
    st.metric("Top Decile Lift", "5.56x", "vs 10% baseline")
    st.markdown("---")
    st.markdown("### 🔗 Links")
    st.markdown("[GitHub](https://github.com/HarshithaPethuraj)")
    st.markdown("[LinkedIn](https://www.linkedin.com/in/harshitha-pethuraj-13738129b/)")
    st.markdown("---")
    st.caption("Built with Streamlit")


# ============================================================
# HERO
# ============================================================
st.markdown("""
<div class="main-title">
    <h1>🏦 Customer Transaction Prediction</h1>
    <p>Banking ML Project · 200K customers · 200 anonymized features · LightGBM champion model</p>
    <div style="margin-top: 0.8rem;">
        <span class="badge">AUC 0.8856</span>
        <span class="badge">AP 0.5818</span>
        <span class="badge">5.56x Lift</span>
        <span class="badge">Threshold 0.25</span>
    </div>
</div>
""", unsafe_allow_html=True)


# ============================================================
# KPI ROW
# ============================================================
col1, col2, col3, col4, col5 = st.columns(5)
kpis = [
    ("0.8856", "Best AUC"),
    ("0.5818", "Avg Precision"),
    ("92.22%", "Accuracy"),
    ("5.56x", "Top-Decile Lift"),
    ("0.25", "Optimal Threshold"),
]
for col, (val, lbl) in zip([col1, col2, col3, col4, col5], kpis):
    with col:
        st.markdown(f"""
        <div class="kpi-card">
            <p class="kpi-value">{val}</p>
            <p class="kpi-label">{lbl}</p>
        </div>
        """, unsafe_allow_html=True)


# ============================================================
# TABS
# ============================================================
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📊 Data Analysis", "🤖 Models", "🎯 Diagnostics", "🔬 Features", "💼 Business"
])


# ============================================================
# TAB 1: DATA
# ============================================================
with tab1:
    st.markdown('<div class="section-h">Target Class Distribution</div>', unsafe_allow_html=True)

    col_a, col_b = st.columns(2)

    with col_a:
        fig, ax = plt.subplots(figsize=(6, 4))
        counts = [44975, 5025]
        labels = ['No Transaction', 'Will Transact']
        bars = ax.bar(labels, counts, color=[PRIMARY, DANGER], edgecolor='white', linewidth=2)
        for bar, count in zip(bars, counts):
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 500,
                   f'{count:,}\n({count/sum(counts)*100:.1f}%)',
                   ha='center', fontweight='bold', fontsize=10)
        ax.set_title('Class Distribution (50K Sample)', fontweight='bold')
        ax.set_ylabel('Customers')
        ax.set_ylim(0, max(counts) * 1.18)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        plt.tight_layout()